### PR TITLE
Added sound for correct/wrong answers

### PR DESCRIPTION
**Pull request by Gauravdarkslayer**
This is a fix for #12 .

- Created function for playing the sound.
- Called that function in case of right / wrong scenario.

CC: @N-Shar-ma

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
That sounds good @Gauravdarkslayer! Could you also add a button with a microphone icon at the top left of the screen to mute / unmute the sound? 

Many players might want to interact with the game quietly so they should have that option easily available

**Comment by Gauravdarkslayer** [comment]
Yes sure! Will do that ! @N-Shar-ma

**Comment by Gauravdarkslayer** [comment]
@N-Shar-ma Here you go, done the required changes, you can check. BTW can you please add hacktoberfest label in this issue ?

**Comment by N-Shar-ma** [comment]
@Gauravdarkslayer Thanks for the contribution! The usage of local storage to persist a user's preference was a really nice touch :)

Since the repository itself is tagged `hacktoberfest`, no other labels, on the issue or PR, should be required to make this count

**Comment by Gauravdarkslayer** [comment]
Yeah @N-Shar-ma , thanks for the review. :)

**Pull request merged**
