### PR TITLE
Famous Companies deck

### PR DESCRIPTION
**Pull request by Girlwithasmile**
Fixes: #21

### CODE REVIEW

**Comment by Girlwithasmile** [comment]
Please can u provide me with a feedback..

**Comment by N-Shar-ma** [comment]
@Girlwithasmile Sorry for the delayed response. The deck is actually quite fun, but 2 major issues are preventing it from being merged. 1st, this information is something that is ever changing so this deck will very soon be outdated - which is why I would have liked you to wait for the issue to be approved by me and then assigned to you. 2nd, there are some hints only Hindi speakers will understand, like for Chanel, which we should avoid to make this accessible to more people across the globe. 

A couple of minor problems are that the matchValues are a little too long, and that you forgot to add the deck to `index.html`

For resolving the 1st issue, you could change the deck to companies instead of CEOs. I believe the other issues are fairly easily solvable. Would be great if you could fix it up, though it would definitely take some rework. Do let me know what you plan to do with this PR next!

**Comment by Girlwithasmile** [comment]
Shall I convert it to founders to prevent problem of ever changing? And change the problematic clues??

**Comment by N-Shar-ma** [comment]
@Girlwithasmile Sounds good! Looking forward to the changes :)

**Comment by N-Shar-ma** [comment]
@Girlwithasmile This is almost ready to merge! 🎉 Could you please explain the emoji sequence for Chanel though? Especially the 2nd emoji?

**Comment by Girlwithasmile** [comment]
Chanel : Its a TV. The emoji is symbolic to remote through which we change channels. And the last is a nail.

**Comment by N-Shar-ma** [comment]
Thanks for contributing this deck @Girlwithasmile ! 🎉

**Pull request merged**
