### PR TITLE
added new cards to old decks

### PR DESCRIPTION
**Pull request by YuriCodes**

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@YuriCodes Thanks for the addition, it fits in well with the rest of the deck! :)

However, since Hacktoberfest rules do not look favourably upon PRs that add an item to a list, could you add at least 2 more cards in this same PR? Those can be in the same or different decks. This is to ensure that your PR isn't classified spam

**Comment by YuriCodes** [comment]
Absolutely!

**Comment by YuriCodes** [comment]
I just added more cards, let me know what you think

**Comment by N-Shar-ma** [comment]
@YuriCodes Those are some sweet additions, thanks for contributing! 😄

**Pull request merged**
